### ISSUE TITLE
Some example posts are not responsive

### ISSUE THREAD

**Issue by eladg** [eladg/ffmpeg-by-example#21]
Currently, this page: https://www.ffmpegbyexample.com/examples/use__colorchannelmixer__filter_to_produce_a_simple_sepia_tones_filter_-82j/

does not change in size. While this example does: https://www.ffmpegbyexample.com/examples/find-keyframes-iframes-of-video/

I suspect that is has to do with the length of text in the syntax code box.

@Speykious can you look into it?

**Comment by Speykious** [comment]
Will do this evening
